---
- name: Converge
  hosts: all
  pre_tasks:
    - name: set basic user fact
      set_fact:
        ansible_user: "{{ lookup('env', 'USER') }}"
      when:
        - ansible_user is undefined

    - name: set basic home fact
      set_fact:
        ansible_user_dir: "{{ lookup('env', 'HOME') }}"
      when:
        - ansible_user_dir is undefined

    - name: set bootc fact
      set_fact:
        ansible_local:
          bootc: false
  roles:
    - role: osp.edpm.edpm_libvirt
      vars:
        edpm_libvirt_tls_cert_src_dir: /tmp/pki
        edpm_libvirt_tls_certs_enabled: true
        edpm_libvirt_password_path: /tmp/libvirtpw
        edpm_libvirt_log_filters_override:
            virtqemud: "1:qemu 2:libvirt 3:object 4:json"
