---
- name: Gather ansible_local facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "local"
  when:
    - ansible_local is not defined

- name: Downloading required packages
  ansible.builtin.dnf:
    name: "{{ edpm_ovs_packages }}"
    download_only: true
    state: "{{ dnf_state | default(omit) }}"
  become: true
  register: _install_packages_result
  until: _install_packages_result is succeeded
  retries: "{{ edpm_ovs_download_retries }}"
  delay: "{{ edpm_ovs_download_delay }}"
  when: ansible_local.bootc is not defined or not ansible_local.bootc
