---
argument_specs:
  # ./roles/edpm_libvirt/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_libvirt role.
    options:
      edpm_libvirt_image_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_libvirt_image_download_retries:
        type: int
        default: 5
      edpm_libvirt_services:
        type: list
        description: The list of libvirt services to run.
        default:
          - "virtlogd"
          - "virtnodedevd"
          - "virtproxyd"
          - "virtqemud"
          - "virtsecretd"
      edpm_libvirt_old_tripleo_compute_sevices:
        type: list
        default:
          - tripleo_nova_libvirt.target
          - tripleo_nova_virtlogd_wrapper.service
          - tripleo_nova_virtnodedevd.service
          - tripleo_nova_virtproxyd.service
          - tripleo_nova_virtqemud.service
          - tripleo_nova_virtsecretd.service
          - tripleo_nova_virtstoraged.service
        description: |
          List of tripleo libvirt services to stop during EDPM adoption
      edpm_libvirt_range:
        type: str
        description: The version range for libvirt package.
        default: ""
      edpm_libvirt_packages:
        type: list
        description: The list of packages to install for libvirt.
        default:
          - libvirt {{edpm_libvirt_range}}
          - libvirt-admin {{edpm_libvirt_range}}
          - libvirt-client {{edpm_libvirt_range}}
          - libvirt-daemon {{edpm_libvirt_range}}
          - qemu-kvm
          - qemu-img
          - libguestfs
          - libseccomp
          - swtpm
          - swtpm-tools
          - edk2-ovmf
          - ceph-common
      edpm_libvirt_ceph_path:
        type: str
        description: The path to the ceph config files.
        default: "/var/lib/openstack/config/ceph"
      edpm_libvirt_tls_certs_enabled:
        type: bool
        default: false
        description: Boolean to specify whether TLS certs are enabled.
      edpm_nova_libvirt_qemu_group:
        type: str
        description: The vhost user socket directory group name.
        default: ''
      edpm_libvirt_log_outputs:
        type: str
        description: Libvirt log output configuration (level:destination format).
        default: "3:journald"
      edpm_libvirt_default_log_filters:
        type: str
        description: Default log filter configuration for all libvirt services.
        default: "3:qemu 3:libvirt 4:object 4:json 4:event 3:util"
      edpm_libvirt_log_filters_defaults:
        type: dict
        description: Dictionary of default log filters for each libvirt service.
        default:
          virtqemud: "{{ edpm_libvirt_default_log_filters }}"
          virtlogd: "{{ edpm_libvirt_default_log_filters }}"
          virtproxyd: "{{ edpm_libvirt_default_log_filters }}"
          virtsecretd: "{{ edpm_libvirt_default_log_filters }}"
          virtnodedevd: "{{ edpm_libvirt_default_log_filters }}"
      edpm_libvirt_log_filters_override:
        type: dict
        description: Dictionary of log filter overrides for specific libvirt services.
        default: {}
      edpm_libvirt_log_filters:
        type: dict
        description: Combined log filters (defaults merged with overrides) for each libvirt service.
        default: "{{ edpm_libvirt_log_filters_defaults | combine(edpm_libvirt_log_filters_override | default({})) }}"
